// IncrementalProperties.sysprop.h - pre-generated sysprop header
// This file is normally generated by sysprop_library at build time
#ifndef INCREMENTAL_PROPERTIES_SYSPROP_H
#define INCREMENTAL_PROPERTIES_SYSPROP_H

// All incremental delivery features disabled by default
// These are stubs for building outside of AOSP

namespace android {
namespace incremental {

inline bool is_incremental_install_enabled() { return false; }

} // namespace incremental
} // namespace android

#endif // INCREMENTAL_PROPERTIES_SYSPROP_H
