// platform_tools_version.h - pre-generated version header
// This file is normally generated by Soong at build time
#ifndef PLATFORM_TOOLS_VERSION_H
#define PLATFORM_TOOLS_VERSION_H

#define PLATFORM_TOOLS_VERSION "33.0.1"

#endif // PLATFORM_TOOLS_VERSION_H
